### ISSUE TITLE
Ability to use raw console to access the container directly.

### ISSUE THREAD

**Issue by Abys5** [wisp-gg/frontend#107]
**This is purely for frontend-related feature requests - requests like subdomain manager, etc. are currently better suited for our [Discord](https://wisp.gg/discord) instead.**

**Is your feature request related to a problem? Please describe.**
As alot of modpack need you to run a bash script to install the pack, i thought a option in the admin panel or a user permission to access the console directly from the panel would be useful.

**Describe the solution you'd like**
The ability to use the panel to access the shell of the docker container

**Comment by Software-Noob** [comment]
This is not a front-end request and rather feature request for the daemon. 

You can currently perform this in the install script or startup parameters. WISP also has modpack manager.

**Comment by WISPdotGG** [comment]
This kinda goes against the point of docker. Ideally the modpack install scripts would be handled automatically when they're installed

**Comment by victiondev** [comment]
We would rather have solutions for the actual root issue than implement fixes like this because as the above comments said, it kinda goes against the point of docker.

We have future plans to handle modpacks which only ship with install scripts, you'll likely hear news about it in our discord closer to the time.
