### ISSUE TITLE
Control - Console permission not working as expected

### ISSUE THREAD

**Issue by mov51** [wisp-gg/frontend#140]
**Describe the bug**
Sub-Users can see the console output even when they don't have the `Control - Console` permission. 

**To Reproduce**
1. Create a Sub-User without the `Control - Console` permission
2. Log in with the Sub-User
3. Navigate to the server and you'll be able to see the console and it's contents

**Expected behavior**
The console window would either not be there or would not show any text when the user does not have the `Control - Console` permission. 

**Screenshots**
![MOV-2022-02-15__8372](https://user-images.githubusercontent.com/16448318/154022345-f8b286b7-dbbc-49a3-8e4d-8e250be65443.png) 
![MOV-2022-02-15__8373](https://user-images.githubusercontent.com/16448318/154022354-03e10737-0eb4-4250-be93-1494118b545e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser  chrome
 - Version v2.0.32

**Comment by sharletp** [comment]
Confirmed, can reproduce though with a few additional caveats, if you were to access the server directly lets say in its offline state or any other where no output is produced then the expected behavior (denied permission due to `Control - Console`) does show up however if any of the Control commands or outputs from the programs are triggered for the console then the output gets populated, a refresh does solve this issue temporarily. 

**Screenshots**
![Peek 2022-02-15 12-24](https://user-images.githubusercontent.com/24799477/154033491-5d4120bd-a40f-4d9e-b56b-55432b203bb9.gif)

**Desktop**
- **OS**: Ubuntu 20.10 Desktop (Linux Distribution)
- **Browser**: Chrome 96.0.4664.110 (Official Build) (64-bit)
- **Version**: v2.0.32

**Comment by victiondev** [comment]
I have a feeling this is related to an issue where you couldn't apply zero permissions to a subuser - are you able to reproduce this now?

**Comment by sharletp** [comment]
> I have a feeling this is related to an issue where you couldn't apply zero permissions to a subuser - are you able to reproduce this now?
@victiondev 

Apologies for the late response, I've tried to reproduce it and can confirm that this issue still exists, as per my prior comment the same case takes place here where the console, if no output comes through it does work as intended however whenever there is a stream of output then it fails to.

**Screenshots**
![Peek 2022-02-21 13-13](https://user-images.githubusercontent.com/24799477/154935089-ee1e168f-f5c0-4d33-9882-c37daac8466f.gif)


**Desktop**
- **OS**: Ubuntu 20.10 Desktop (Linux Distribution)
- **Browser**: Chrome 96.0.4664.110 (Official Build) (64-bit)
- **Version**: v2.0.52
