### ISSUE TITLE
DISCORD OAUHT2

### ISSUE THREAD

**Issue by zapz12** [wisp-gg/frontend#255]
### Describe the feature and why you would like to see it.

Nearly everyone who uses the panel has a discord account so why not add discord oauth2 as an option. 

### Describe the solution you'd like.

Discord login option

**Comment by victiondev** [comment]
What's the added benefit from this? In theory this system will only automatically create the account for you & atm we don't have a register function meaning you'd have to have an existing account to link to discord anyway - which removes the whole point of this.

I don't see what this brings other than extra useless configuration for panel admins (having to input discord client credentials) otherwise it's a technical limitation to whitelabel the discord oauth if we only use our own discord client
