### ISSUE TITLE
Modpack Manager - Mods Missing

### ISSUE THREAD

**Issue by falceso** [wisp-gg/frontend#301]
### Describe the bug

Using the Modpack Manager to install [Create: Above and Beyond](https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond) two mods are consistently missing when installed, Darker Depths and SoundFilter. These mods missing results in players attempting to join fail for inconsistent modpack list.

### Expected Behavior

The modpack installer fully installs the modpack requested fully and consistently, with all the necessary mods as provided by the Modpack Developer.

### Actual Behavior

Modpack Manager somehow skips these two mods, Darker Depths and SoundFilter.

### Steps to Reproduce

Step 1 - Use Modpack Manager to download the Create: Above and Beyond modpack, with reformat option.
Step 2 - Compare differences between the CurseForge Server Pack and the Modpack generated by Wisp.
Step 3 - See the difference.

### Browser Details

Chrome 102

### Operating System

Windows 10

**Comment by TrixterTheTux** [comment]
Sound filters are purposefully blacklisted due to mentioning on their [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/sound-filters) that it is clientside only - unless there's some specific reason why it should be on the server as from my testing it will usually crash the server. Though I'm looking into why Darker Depths got blacklisted as seems other modpack had issues with it causing it to be blacklisted for this modpack.

**Comment by falceso** [comment]
> SoundFilters clientside only
While probably true, if there's a modpack that leaves the mod in the server, then there will be a mismatch in mod list. Fortunately, it doesn't appear to crash the server at least when using Create and Beyond.

**Comment by TrixterTheTux** [comment]
The system has been refactored to have version-specific blacklists (instead of assuming that certain versions would always be broken, thus other modpacks being able to affect each other), so this should be now fixed. Though there are still certain edge cases for some modpacks that are on my to-do list to look into, at least with this change should be a lot rarer.
