### ISSUE TITLE
Re-add thumbnails for servers by making them bigger

### ISSUE THREAD

**Issue by JouanDeag** [wisp-gg/frontend#56]
**Describe the solution you'd like**
Please re-add thumbnails for servers by making them bigger. Otherwise the egg thumbnails are kinda useless.

**Comment by WISPdotGG** [comment]
"At the current state I think the client side looks more like a admin side since a user typically doesn't have more than 1-2 server which is why I think these tiny thumbnails look kinda silly when you are just gonna have a mostly blank page"

"I liked the old card design. Fills the page, nice background and there's more to click on for navigation"

**Comment by krenny** [comment]
Yeah this new server cards just look ugly :(

**Comment by drizmans** [comment]
Done in 0cfc51c
