### ISSUE TITLE
Panel can't connect to daemon behind CloudFlare proxy

### ISSUE THREAD

**Issue by ianleckey** [wisp-gg/frontend#70]
Even with this selected
![image](https://user-images.githubusercontent.com/668964/153767682-8c724505-fea8-40ec-91d7-4e89ee97c3cc.png)

Or with `enabled: false` in the SSL block of `config/wisp.yaml` - the panel still can't connect to the daemon if it's running behind CloudFlare's proxy.

**Comment by TrixterTheTux** [comment]
At the moment, you can't run the daemon behind Cloudflare due to not having any control over where the FQDN points on our end, thus always bypassing CF. This change will be revisited at some point, but probably only after we look into allowing users to change where the FQDN points (e.g. for DDNS) on the billing dashboard.
